### ISSUE TITLE
Shouldn't activation be after the batch norm layer?

### ISSUE THREAD

**Issue by ag1988** [geifmany/cifar-vgg#5]
Apologies in advance; I am new to this stuff. 

Thanks,
Ankit

**Comment by geifmany** [comment]
Both works, You are right that in the original bathnorm paper they put it before, but it is also works the other way.
Actually there is a debate what the right form, some people do before and some after.

**Comment by ag1988** [comment]
I see..interesting. I'll check the paper to see why this is the case. 
Anyways, thanks for the prompt response!

Regards,
Ankit

**Comment by geifmany** [comment]
You are welcome. It is not the best source but you can read more about it here
https://www.reddit.com/r/MachineLearning/comments/67gonq/d_batch_normalization_before_or_after_relu/ <https://www.reddit.com/r/MachineLearning/comments/67gonq/d_batch_normalization_before_or_after_relu/>

**Comment by ag1988** [comment]
This is great. Thanks for your help Yonathan.
