### ISSUE TITLE
Stuck at first Epoch

### ISSUE THREAD

**Issue by debadridtt** [geifmany/cifar-vgg#6]
I cloned the repository and its stuck at displaying "Epoch 1/250" and no training is happening.  Also I doubt where is the cifar10 dataset getting downloaded?  `cifar10.load_data()` right? Is it that because its downloading the dataset, that's why its stuck at Epoch 1/250? Once it gets downloaded the training will start?

P.S. I don't have GPU.

**Comment by geifmany** [comment]
Just wait a little bit more time.
You can change the verbose value of the fit function to see the progress during a batch.
